sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t maharjansudhan/npbargain -f Dockerfile.dev .

script:
  - docker run -e CI=true maharjansudhan/npbargain npm run test -- --coverage